/**
 * Display names for manufacturers and importers.
 *
 * The registry's `tozeret_nm` is brand + country of manufacture in one
 * fixed-width, truncated field ("פולקסווגן גרמנ", "שברולט ד.קוריא"). Shown as-is
 * it reads like a brand called "Hyundai Turkey". So the name is split into its
 * two real parts, in this order of trust:
 *
 *  1. The Ministry's own model catalogue, which publishes brand and country as
 *     separate columns per manufacturer code (shared/manufacturers.json,
 *     generated by scripts/build-manufacturers.mjs). Covers ~99.7% of cars.
 *
 * Shared by the web app and the native app (imported as `@shared/manufacturer`).
 *  2. For codes the catalogue lacks (old buses, motorcycles, new makers), the
 *     country is peeled off the end of the registry string — but only when the
 *     tail is recognisably a country. Otherwise the string is left whole: an
 *     untidy name is better than a wrong one.
 *
 * On top of that, only *spelling* is normalised — the Ministry writes the same
 * brand several ways ("אודי"/"אאודי", "מרצדס"/"מרצדס בנץ"). No brand is ever
 * mapped to a different company.
 */
import catalogue from './manufacturers.json';

/** A raw data.gov.il field value. Declared here so both apps can share this file. */
type CkanValue = string | number | boolean | null;

interface CatalogueEntry {
  cd: number;
  brand: string | null;
  country: string | null;
  names: string[];
}

export interface Manufacturer {
  /** "יונדאי" */
  brand: string;
  /** "טורקיה", or null when it can't be told with confidence. */
  country: string | null;
}

/**
 * Same company, different Ministry spellings → one display form. Brands sold
 * in Israel under a Latin initialism use it, since that is how they're known.
 */
const BRAND_ALIASES: Readonly<Record<string, string>> = {
  'אודי': 'אאודי',
  'דאציה': "דאצ'יה",
  'מרצדס': 'מרצדס-בנץ',
  'מרצדס בנץ': 'מרצדס-בנץ',
  'דימלרקריזלר': 'דיימלר-קרייזלר',
  'האמר ג.מ': 'האמר',
  'לנדרובר': 'לנד רובר',
  'ימהה': 'ימאהה',
  'ב מ וו': 'ב.מ.וו',
  'מ.ג': 'MG',
  'בי ווי די': 'BYD',
  "ג'י.אמ.סי": 'GMC',
  'גי.אי.סי': 'GAC',
  'גיי.איי.סי': 'GAC',
  'די אס': 'DS',
  'אף אי דאבל יו': 'FAW',
  'קיי גי מוביליט': 'KGM',
  'אל אי וי סי': 'LEVC',
  'אל.טי.איי.': 'LTI',
  'איי אם': 'IM',
  'אס דאבל יו אמ': 'SWM',
  'די.אף.אס.קיי': 'DFSK',
  // Motorcycles
  'קי.טי.אמ': 'KTM',
  'קי.טי.אם': 'KTM',
  'קי טי אם': 'KTM',
  'הסקוורנה': 'הוסקוורנה',
  'הוסקוורנאה': 'הוסקוורנה',
  'טריאומף': 'טריומף',
  'רויאל אנפלד': 'רויאל אנפילד',
  'אנפילד': 'רויאל אנפילד',
  'גאסגאס': 'GASGAS',
  'גאס גאס': 'GASGAS',
  'ב ס א': 'BSA',
  'מ.וו אגוסטא': 'MV אגוסטא',
};

/** Ministry country spellings (full, abbreviated, misspelt) → one display form. */
const COUNTRY_ALIASES: Readonly<Record<string, string>> = {
  'ארהב"': 'ארה"ב',
  "ארה''ב": 'ארה"ב',
  'ארהב': 'ארה"ב',
  'ארה': 'ארה"ב',
  'ד אפריקה': 'דרום אפריקה',
  'ד.אפ': 'דרום אפריקה',
  'ד. קוריאה': 'דרום קוריאה',
  'ד.קוריאה': 'דרום קוריאה',
  'ד.קוריא': 'דרום קוריאה',
  'ד.קור': 'דרום קוריאה',
  'קוריאה הדרומית': 'דרום קוריאה',
  'תורכיה': 'טורקיה',
  'מכסיקו': 'מקסיקו',
  'אנגליה': 'בריטניה',
  'טאיוון': 'טייוואן',
  'טיוואן': 'טייוואן',
  'טיואן': 'טייוואן',
  'ויטנאם': 'וייטנאם',
  'ויאטנם': 'וייטנאם',
  // "אלפא רומיאו_אי": the only two-letter tail in the registry.
  'אי': 'איטליה',
};

/** Every country the registry uses, in display form — for recognising tails. */
const COUNTRIES = [
  'אוסטריה', 'איטליה', 'אינדונזיה', 'ארגנטינה', 'ארה"ב', 'בלגיה', 'ברזיל', 'בריטניה',
  'גרמניה', 'דרום אפריקה', 'דרום קוריאה', 'הודו', 'הולנד', 'הונגריה', 'וייטנאם',
  'טורקיה', 'טייוואן', 'יפן', 'ישראל', 'מקסיקו', 'מרוקו', 'סין', 'סלובניה', 'סלובקיה',
  'ספרד', 'סרביה', 'פולין', 'פורטוגל', 'פינלנד', "צ'כיה", 'צרפת', 'קנדה', 'רומניה',
  'רוסיה', 'שבדיה', 'שוויץ', 'תאילנד',
];

/** Registry spellings that are prefixes of a country but not of its display form. */
const COUNTRY_SPELLINGS: ReadonlyArray<[string, string]> = [
  ...COUNTRIES.map((c): [string, string] => [c, c]),
  ...Object.entries(COUNTRY_ALIASES),
  ['אנגליה', 'בריטניה'],
  ['טורקי', 'טורקיה'],
  ['תאילנ', 'תאילנד'],
  ['אינדונזי', 'אינדונזיה'],
];

const BY_CODE = new Map<number, CatalogueEntry>();
const BY_NAME = new Map<string, CatalogueEntry>();
for (const entry of catalogue as CatalogueEntry[]) {
  BY_CODE.set(entry.cd, entry);
  for (const name of entry.names) BY_NAME.set(name, entry);
}

function tidy(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

export function normalizeBrand(brand: string): string {
  const clean = tidy(brand);
  return BRAND_ALIASES[clean] ?? clean;
}

export function normalizeCountry(country: string): string | null {
  const clean = tidy(country);
  if (!clean) return null;
  return COUNTRY_ALIASES[clean] ?? clean;
}

/**
 * The countries a (possibly truncated) tail could be. Min three letters for a
 * prefix match, so a stray short word is never mistaken for a country.
 */
function countriesMatching(tail: string): Set<string> {
  const matches = new Set<string>();
  for (const [spelling, display] of COUNTRY_SPELLINGS) {
    if (spelling === tail || (tail.length >= 3 && spelling.startsWith(tail))) {
      matches.add(display);
    }
  }
  return matches;
}

/**
 * Peel a country off the end of a registry name. Tries a two-word tail first
 * ("ד. קוריאה", "ד אפריקה"), then one word. Separators in the registry are a
 * space, a hyphen ("פולקסווגן-ספרד") or an underscore ("לוטוס_אנגליה").
 */
export function splitRegistryName(raw: string): Manufacturer {
  const name = tidy(raw);
  let parts = name.split(/(?<=\S)[\s_-]+(?=\S)/);
  // "סי.אף.מוטו.סין": dots also separate initials, so only the final dot is a
  // candidate, and only when nothing else split the name.
  if (parts.length === 1 && name.includes('.')) {
    const at = name.lastIndexOf('.');
    parts = [name.slice(0, at), name.slice(at + 1)].filter(Boolean);
  }

  for (const size of [2, 1]) {
    if (parts.length <= size) continue;
    const tail = parts.slice(-size).join(' ');
    const matches = countriesMatching(tail);
    if (matches.size === 0) continue;
    return {
      brand: normalizeBrand(parts.slice(0, -size).join(' ')),
      // A truncated tail like "סלוב" is clearly a country, but which one isn't.
      country: matches.size === 1 ? ([...matches][0] ?? null) : null,
    };
  }
  return { brand: normalizeBrand(name), country: null };
}

function fromCatalogue(entry: CatalogueEntry | undefined, raw: string): Manufacturer | null {
  if (!entry?.brand) return null;
  return {
    brand: normalizeBrand(entry.brand),
    country: entry.country ? normalizeCountry(entry.country) : splitRegistryName(raw).country,
  };
}

/**
 * Resolve a registry record's manufacturer. `tozeret_eretz_nm` is the separate
 * country column that some datasets (motorcycles) carry.
 */
export function resolveManufacturer(record: {
  tozeret_cd?: CkanValue;
  tozeret_nm?: CkanValue;
  tozeret_eretz_nm?: CkanValue;
}): Manufacturer | null {
  const raw = tidy(String(record.tozeret_nm ?? ''));
  if (!raw || raw.toLowerCase() === 'null') return null;

  const code = Number(record.tozeret_cd);
  const known =
    fromCatalogue(Number.isInteger(code) ? BY_CODE.get(code) : undefined, raw) ??
    fromCatalogue(BY_NAME.get(raw), raw);
  if (known) return known;

  const split = splitRegistryName(raw);
  const hint = tidy(String(record.tozeret_eretz_nm ?? ''));
  return hint && hint.toLowerCase() !== 'null'
    ? { brand: split.brand, country: normalizeCountry(hint) }
    : split;
}

/**
 * The brand alone, from whatever string is at hand — including a raw registry
 * name saved by an older version of the recent-searches list.
 */
export function displayBrand(nameOrBrand: string): string {
  return resolveManufacturer({ tozeret_nm: nameOrBrand })?.brand ?? tidy(nameOrBrand);
}

/**
 * Importer names as published in the price list, with the dataset's encoding
 * damage undone:
 *  - numbers stored in visual order ("מאי מוטורס )5102( בע"מ" → "(2015)"),
 *  - doubled spaces, and
 *  - the legal suffix, which the fixed-width field often truncates to "בע".
 */
export function displayImporter(raw: string, now: Date = new Date()): string {
  let name = tidy(raw);

  // A mirrored pair wraps its content as ")…(" in visual order. Space it from
  // its neighbours, which the fixed-width field sometimes glues together.
  name = name.replace(/\s*\)([^()]*)\(\s*/g, ' ($1) ');

  // A four-digit run that is a plausible year only when read backwards was
  // stored reversed. Anything else — including a "year" in the future — is
  // left exactly as published.
  const isYear = (s: string) => /^(19|20)\d\d$/.test(s) && Number(s) <= now.getFullYear();
  name = name.replace(/\d{4}/g, (digits) => {
    const reversed = [...digits].reverse().join('');
    return !isYear(digits) && isYear(reversed) ? reversed : digits;
  });

  // Whole word only, so a name that merely ends in those letters is untouched.
  name = tidy(name).replace(/\s+(?:בע"מ|בע''מ|בעמ|בע"|בע)$/, '');
  return tidy(name);
}
